"use strict";
let token=sessionStorage.getItem("sad_token")||"",account=null,currentQuest=null;
const $=id=>document.getElementById(id);
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data}
function message(text,error=false){$("notice").textContent=text;$("notice").className=error?"notice error":"notice"}
function showView(id){document.querySelectorAll(".view").forEach(x=>x.hidden=x.id!==id);document.querySelectorAll("nav button").forEach(x=>{const active=x.dataset.view===id;x.classList.toggle("active",active);if(active)x.setAttribute("aria-current","page");else x.removeAttribute("aria-current")});if(id==="dashboard")loadDashboard();if(id==="accounts")loadAccounts();if(id==="forge")loadProgress();if(id==="classroom")loadClassroom();const heading=$(id)?.querySelector("h2");if(heading)heading.focus()}
function buildNav(){const items=[["study","Personal Study"]];if(["student","teacher","owner"].includes(account.role))items.push(["forge","Forge Student"]);if(["teacher","owner"].includes(account.role))items.push(["classroom","Student Progress"]);if(["owner","developer","reviewer","viewer"].includes(account.role))items.push(["dashboard","Dev Dashboard"]);if(account.role==="owner")items.push(["accounts","Accounts"]);items.push(["settings","Security"]);$("nav").replaceChildren(...items.map(([id,label])=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.dataset.view=id;b.setAttribute("aria-controls",id);b.onclick=()=>showView(id);return b}));showView(items[0][0])}
async function enter(){const me=await api("/v1/auth/me");account=me.account;$("login").hidden=true;$("app").hidden=false;$("welcome").textContent=`Welcome, ${me.profile.display_name}`;$("role").textContent=account.role;buildNav()}
$("login-form").onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{const data=await api("/v1/auth/login",{method:"POST",body:JSON.stringify(body)});token=data.token;sessionStorage.setItem("sad_token",token);await enter()}catch(err){$("login-error").textContent=err.message}};
$("logout").onclick=async()=>{try{await api("/v1/auth/logout",{method:"POST",body:"{}"})}finally{sessionStorage.clear();location.reload()}};
$("study-form").onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target),body=Object.fromEntries(form);body.graded=form.has("graded");body.generate=true;if(body.target_word_count)body.target_word_count=Number(body.target_word_count);else delete body.target_word_count;try{message("Generating…");const data=await api("/v1/study/plan",{method:"POST",body:JSON.stringify(body)});const out=$("study-output");out.hidden=false;out.textContent=data.result?.content||data.instruction;message(data.result?.status==="generated"?"Study response ready.":"Plan ready; local model is not configured.")}catch(err){message(err.message,true)}};
$("quest-form").onsubmit=async e=>{e.preventDefault();try{currentQuest=await api("/v1/forge/quests",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const out=$("quest-output");out.hidden=false;out.textContent=`${currentQuest.title}\n\nObjective: ${currentQuest.objective}\n\nChallenge: ${currentQuest.challenges.join("\n")}\n\nBoss check: ${currentQuest.boss_check}`;$("quest-actions").hidden=false;message("Quest created.")}catch(err){message(err.message,true)}};
$("hint").onclick=async()=>{if(!currentQuest)return;try{const d=await api("/v1/forge/hint",{method:"POST",body:JSON.stringify({quest_id:currentQuest.quest_id})});message(`Hint level: ${d.hint_level.replaceAll("_"," ")}`)}catch(err){message(err.message,true)}};
$("complete-form").onsubmit=async e=>{e.preventDefault();if(!currentQuest)return;const form=new FormData(e.target);try{const d=await api("/v1/forge/complete",{method:"POST",body:JSON.stringify({quest:currentQuest,score:Number(form.get("score"))/100,boss_passed:form.has("boss_passed")})});await loadProgress();message(d.outcome.mastered?`Mastered! You now have ${d.outcome.xp} XP.`:"Not mastered yet. Review the method and try the boss check again.")}catch(err){message(err.message,true)}};
async function loadProgress(){try{const p=await api("/v1/forge/progress");$("progress").innerHTML=`<div class="stat"><b>${escapeText(p.xp)}</b><br>XP</div><div class="stat"><b>${escapeText(p.rank)}</b><br>Rank</div><div class="stat"><b>${escapeText(p.companion_stage)}</b><br>Companion stage</div>`}catch(err){message(err.message,true)}}
async function loadDashboard(){try{const d=await api("/v1/dashboard");const failures=d.failures.map(f=>`<tr><td>${escapeText(f.summary)}</td><td>${escapeText(f.state)}</td><td>${failureActions(f)}</td></tr>`).join("");const jobs=d.development.map(j=>`<tr><td>${escapeText(j.work_item_id.slice(0,8))}</td><td>${escapeText(j.state)}</td><td>${jobActions(j)}</td></tr>`).join("");$("dashboard-output").innerHTML=`<h3>Failure inbox</h3><table><caption>Failure inbox</caption><thead><tr><th scope="col">Failure</th><th scope="col">State</th><th scope="col">Human action</th></tr></thead><tbody>${failures}</tbody></table><h3>Forge jobs</h3><table><caption>Forge jobs</caption><thead><tr><th scope="col">Job</th><th scope="col">State</th><th scope="col">Human action</th></tr></thead><tbody>${jobs}</tbody></table>`}catch(err){message(err.message,true)}}
function action(label,path,body={}){return `<button class="dash-action secondary" data-path="${path}" data-body='${JSON.stringify(body)}'>${label}</button>`}
function failureActions(f){let out="";if(f.state==="new"&&["owner","reviewer"].includes(account.role))out+=action("Review",`/v1/failures/${f.failure_id}/review`);if(["new","in_review"].includes(f.state)&&account.role==="owner")out+=action("Push to development",`/v1/failures/${f.failure_id}/push`,{approved:true});return out||"—"}
function jobActions(j){if(j.state==="triaged"&&account.role==="owner")return action("Approve isolation",`/v1/jobs/${j.work_item_id}/approve-isolated`,{source_snapshot:"owner-ui"});if(j.state==="approved_for_isolated_work"&&["owner","developer"].includes(account.role))return action("Run isolated tests",`/v1/jobs/${j.work_item_id}/execute`);if(j.state==="awaiting_human_decision"&&["owner","reviewer"].includes(account.role))return action("Approve",`/v1/jobs/${j.work_item_id}/decision`,{decision:"approve"})+action("Reject",`/v1/jobs/${j.work_item_id}/decision`,{decision:"reject"});if(["approved","rejected"].includes(j.state)&&account.role==="owner")return action("Close",`/v1/jobs/${j.work_item_id}/close`);return "—"}
$("dashboard-output").onclick=async e=>{const b=e.target.closest(".dash-action");if(!b)return;try{await api(b.dataset.path,{method:"POST",body:b.dataset.body});await loadDashboard();message("Workflow updated.")}catch(err){message(err.message,true)}};
$("refresh-dashboard").onclick=loadDashboard;
async function loadClassroom(){try{const d=await api("/v1/students");$("classroom-output").innerHTML=`<table><caption>Student progress</caption><thead><tr><th scope="col">Student</th><th scope="col">XP</th><th scope="col">Rank</th><th scope="col">Completed</th></tr></thead><tbody>${d.students.map(s=>`<tr><td>${escapeText(s.username)}</td><td>${escapeText(s.progress.xp)}</td><td>${escapeText(s.progress.rank)}</td><td>${escapeText(s.progress.completed_quests.length)}</td></tr>`).join("")}</tbody></table>`}catch(err){message(err.message,true)}}
$("refresh-classroom").onclick=loadClassroom;
async function loadAccounts(){try{const d=await api("/v1/accounts");$("accounts-output").innerHTML=`<table><caption>Account permissions</caption><thead><tr><th scope="col">Username</th><th scope="col">Role</th><th scope="col">Status</th><th scope="col">Control</th></tr></thead><tbody>${d.accounts.map(a=>`<tr><td>${escapeText(a.username)}</td><td>${escapeText(a.role)}</td><td>${a.active?"Active":"Disabled"}</td><td>${a.role==="owner"?"Protected":`<button class="account-toggle secondary" data-id="${a.account_id}" data-active="${!a.active}">${a.active?"Disable":"Enable"}</button>`}</td></tr>`).join("")}</tbody></table>`}catch(err){message(err.message,true)}}
$("accounts-output").onclick=async e=>{const b=e.target.closest(".account-toggle");if(!b)return;try{await api(`/v1/accounts/${b.dataset.id}/active`,{method:"POST",body:JSON.stringify({active:b.dataset.active==="true"})});await loadAccounts();message("Account status updated.")}catch(err){message(err.message,true)}};
$("account-form").onsubmit=async e=>{e.preventDefault();try{await api("/v1/accounts",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();await loadAccounts();message("Account created.")}catch(err){message(err.message,true)}};
$("password-form").onsubmit=async e=>{e.preventDefault();try{await api("/v1/auth/password",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();message("Password changed. Other sessions were signed out.")}catch(err){message(err.message,true)}};
function escapeText(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
if(token)enter().catch(()=>{sessionStorage.clear();token=""});
