"use strict";
let token=sessionStorage.getItem("sad_token")||"",account=null,currentQuest=null;
const $=id=>document.getElementById(id);
const FORGE_RANKS=[["Initiate",0],["Apprentice",100],["Journeyman",300],["Expert",700],["Master",1500]];
const COMPANION_STAGES=["Initiate Egg","Apprentice Companion","Journeyman Companion","Expert Companion","Master Companion"];
const HINT_LEVELS=["nudge","stronger_hint","worked_example","explanation"];
const STARTER_LESSONS=[
  {subject:"Python",title:"Variables",objective:"Store and reuse information with clear variable names",assignment:'Create a variable named robot_name that stores the text "Bolt". Then explain why text needs quotation marks.'},
  {subject:"Python",title:"Decisions",objective:"Use a condition to make a program choose an action",assignment:"Write an if statement that checks whether score is at least 10. Explain what >= means and why the line ends with a colon."},
  {subject:"Python",title:"Loops",objective:"Repeat a useful action without copying code",assignment:"Write the first line of a for loop that repeats three times. Explain what range(3) produces."},
  {subject:"AI literacy",title:"Fact check",objective:"Test an AI answer before trusting or sharing it",assignment:"List three ways to check an AI-generated claim. Identify which source you would trust most and explain why."},
  {subject:"Math",title:"Fraction mission",objective:"Find equivalent fractions and explain the method",assignment:"Find two fractions equivalent to 3/4. Show how multiplication creates each equivalent fraction."},
  {subject:"Writing",title:"Strong paragraph",objective:"Build a paragraph with a claim, evidence and explanation",assignment:"Write one paragraph explaining why practice improves a skill. Include a clear claim, one example and an explanation connecting the example to the claim."},
];
async function api(path,options={}){const mobileHeaders=window.SADMobile?.headers?.()||{};const headers={"Content-Type":"application/json",...mobileHeaders,...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});const data=await response.json();if(!response.ok){window.SADMobile?.handleApiError?.(data.error||"Request failed");throw new Error(data.error||"Request failed")}return data}
function message(text,error=false){$("notice").textContent=text;$("notice").className=error?"notice error":"notice"}
function showView(id){document.querySelectorAll(".view").forEach(x=>x.hidden=x.id!==id);document.querySelectorAll("nav button").forEach(x=>{const active=x.dataset.view===id;x.classList.toggle("active",active);if(active)x.setAttribute("aria-current","page");else x.removeAttribute("aria-current")});if(id==="dashboard")loadDashboard();if(id==="accounts")loadAccounts();if(id==="forge")loadProgress();if(id==="classroom")loadClassroom();if(id==="mobile")loadMobileDevices();if(id==="system")loadSystemReadiness();const heading=$(id)?.querySelector("h2");if(heading)heading.focus()}
function buildNav(){const items=[["study","Personal Study"]];if(["student","teacher","owner"].includes(account.role))items.push(["forge","Forge Student"]);if(["teacher","owner"].includes(account.role))items.push(["classroom","Student Progress"]);if(["owner","developer","reviewer","viewer"].includes(account.role))items.push(["dashboard","Dev Dashboard"]);if(account.role==="owner"){items.push(["accounts","Accounts"]);items.push(["mobile","Mobile Access"]);items.push(["system","System Status"])}items.push(["settings","Security"]);$("nav").replaceChildren(...items.map(([id,label])=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.dataset.view=id;b.setAttribute("aria-controls",id);b.onclick=()=>showView(id);return b}));showView(items[0][0])}
async function enter(){const me=await api("/v1/auth/me");account=me.account;$("login").hidden=true;$("pairing").hidden=true;$("app").hidden=false;$("welcome").textContent=`Welcome, ${me.profile.display_name}`;$("role").textContent=account.role;$("forget-device").hidden=!window.SADMobile?.remote;buildNav()}
$("login-form").onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{const data=await api("/v1/auth/login",{method:"POST",body:JSON.stringify(body)});token=data.token;sessionStorage.setItem("sad_token",token);await enter()}catch(err){$("login-error").textContent=err.message}};
$("logout").onclick=async()=>{try{await api("/v1/auth/logout",{method:"POST",body:"{}"})}finally{sessionStorage.removeItem("sad_token");location.reload()}};
$("study-form").onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target),body=Object.fromEntries(form);body.graded=form.has("graded");body.generate=true;if(body.target_word_count)body.target_word_count=Number(body.target_word_count);else delete body.target_word_count;try{message("Generating…");const data=await api("/v1/study/plan",{method:"POST",body:JSON.stringify(body)});const out=$("study-output");out.hidden=false;out.textContent=data.result?.content||data.instruction;message(data.result?.status==="generated"?"Study response ready.":"Plan ready; local model is not configured.")}catch(err){message(err.message,true)}};

function rankProgress(xp,rank){const index=Math.max(0,FORGE_RANKS.findIndex(([name])=>name===rank));if(index>=FORGE_RANKS.length-1)return{percent:100,next:"Master",remaining:0};const current=FORGE_RANKS[index][1],next=FORGE_RANKS[index+1][1];const percent=Math.max(0,Math.min(100,Math.round(((xp-current)/(next-current))*100)));return{percent,next:FORGE_RANKS[index+1][0],remaining:Math.max(0,next-xp)}}
function renderForgeProgress(p){const xp=Number(p.xp)||0,rank=String(p.rank||"Initiate"),completed=Array.isArray(p.completed_quests)?p.completed_quests.length:0,stage=Math.max(0,Math.min(4,Number(p.companion_stage)||0)),track=rankProgress(xp,rank);$("progress").innerHTML=`<div class="forge-stat"><strong>${escapeText(xp)} XP</strong><span>${track.remaining?`${escapeText(track.remaining)} XP to ${escapeText(track.next)}`:"Top rank reached"}</span><div class="xp-track" aria-label="Rank progress"><span class="xp-fill" style="width:${track.percent}%"></span></div></div><div class="forge-stat"><strong>${escapeText(rank)}</strong><span>Current rank</span></div><div class="forge-stat"><strong>${escapeText(completed)}</strong><span>Quests mastered</span></div>`;$("companion-name").textContent=COMPANION_STAGES[stage];$("companion-note").textContent=stage>=4?"Final Alpha stage reached.":`${Math.max(0,3-(completed%3))||3} mastered quest${Math.max(0,3-(completed%3))===1?"":"s"} to next evolution.`;$("companion-orb").className=`companion-orb stage-${stage}`;window.SadAvatar?.setCompanionStage(stage);document.querySelectorAll("#rank-path li").forEach(li=>{const liIndex=FORGE_RANKS.findIndex(([name])=>name===li.dataset.rank);const currentIndex=FORGE_RANKS.findIndex(([name])=>name===rank);li.classList.toggle("complete",liIndex<currentIndex);li.classList.toggle("current",liIndex===currentIndex)})}
function resetHintLadder(){document.querySelectorAll("#hint-ladder li").forEach(li=>li.classList.remove("used","current"));$("hint-status").textContent="No hints used yet."}
function markHintLevel(level){const index=HINT_LEVELS.indexOf(level);document.querySelectorAll("#hint-ladder li").forEach((li,i)=>{li.classList.toggle("used",i<index);li.classList.toggle("current",i===index)});$("hint-status").textContent=`Unlocked: ${level.replaceAll("_"," ")}.`}
function renderLessonLibrary(){
  const library=$("lesson-library");
  if(!library)return;
  library.replaceChildren(...STARTER_LESSONS.map((lesson,index)=>{
    const button=document.createElement("button");button.type="button";button.className="starter-lesson";button.dataset.lesson=String(index);
    const subject=document.createElement("small");subject.textContent=lesson.subject;
    const title=document.createElement("strong");title.textContent=lesson.title;
    const action=document.createElement("span");action.textContent="Load lesson →";
    button.append(subject,title,action);return button;
  }));
  library.onclick=event=>{
    const button=event.target.closest(".starter-lesson");if(!button)return;
    const lesson=STARTER_LESSONS[Number(button.dataset.lesson)];if(!lesson)return;
    const form=$("quest-form");form.elements.subject.value=lesson.subject;form.elements.learning_objective.value=lesson.objective;form.elements.assignment.value=lesson.assignment;
    $("lesson-library-status").textContent=`${lesson.title} loaded. Review it, then create the quest.`;form.elements.assignment.focus();
  };
}

$("quest-form").onsubmit=async e=>{e.preventDefault();try{currentQuest=await api("/v1/forge/quests",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$("active-quest").hidden=false;$("quest-title").textContent=currentQuest.title;$("quest-subject").textContent=currentQuest.subject;$("quest-objective").textContent=`Objective: ${currentQuest.objective}`;$("boss-prompt").textContent=currentQuest.boss_check;const out=$("quest-output");out.hidden=false;out.textContent=currentQuest.challenges.join("\n\n");$("quest-actions").hidden=false;resetHintLadder();out.focus();message("Quest forged. Clear the challenge, then face the boss gate.")}catch(err){message(err.message,true)}};
$("hint").onclick=async()=>{if(!currentQuest)return;try{const d=await api("/v1/forge/hint",{method:"POST",body:JSON.stringify({quest_id:currentQuest.quest_id})});markHintLevel(d.hint_level);message(`Hint unlocked: ${d.hint_level.replaceAll("_"," ")}.`)}catch(err){message(err.message,true)}};
$("complete-form").onsubmit=async e=>{e.preventDefault();if(!currentQuest)return;const form=new FormData(e.target);try{const d=await api("/v1/forge/complete",{method:"POST",body:JSON.stringify({quest:currentQuest,score:Number(form.get("score"))/100,boss_passed:form.has("boss_passed")})});await loadProgress();if(d.outcome.mastered){$("quest-subject").textContent="MASTERED";message(`Quest mastered! ${d.outcome.xp} total XP. Companion and rank progress updated.`)}else message("Boss gate held. Review the method, use a hint if needed, and try again.")}catch(err){message(err.message,true)}};
async function loadProgress(){try{const p=await api("/v1/forge/progress");renderForgeProgress(p)}catch(err){message(err.message,true)}}

async function loadDashboard(){try{const d=await api("/v1/dashboard");const failures=d.failures.map(f=>`<tr><td>${escapeText(f.summary)}</td><td>${escapeText(f.state)}</td><td>${failureActions(f)}</td></tr>`).join("");const jobs=d.development.map(j=>`<tr><td>${escapeText(j.work_item_id.slice(0,8))}</td><td>${escapeText(j.state)}</td><td>${jobActions(j)}</td></tr>`).join("");$("dashboard-output").innerHTML=`<h3>Failure inbox</h3><table><caption>Failure inbox</caption><thead><tr><th scope="col">Failure</th><th scope="col">State</th><th scope="col">Human action</th></tr></thead><tbody>${failures}</tbody></table><h3>Forge jobs</h3><table><caption>Forge jobs</caption><thead><tr><th scope="col">Job</th><th scope="col">State</th><th scope="col">Human action</th></tr></thead><tbody>${jobs}</tbody></table>`}catch(err){message(err.message,true)}}
function action(label,path,body={}){return `<button class="dash-action secondary" data-path="${path}" data-body='${JSON.stringify(body)}'>${label}</button>`}
function failureActions(f){let out="";if(f.state==="new"&&["owner","reviewer"].includes(account.role))out+=action("Review",`/v1/failures/${f.failure_id}/review`);if(["new","in_review"].includes(f.state)&&account.role==="owner")out+=action("Push to development",`/v1/failures/${f.failure_id}/push`,{approved:true});return out||"—"}
function jobActions(j){if(j.state==="triaged"&&account.role==="owner")return action("Approve isolation",`/v1/jobs/${j.work_item_id}/approve-isolated`,{source_snapshot:"owner-ui"});if(j.state==="approved_for_isolated_work"&&["owner","developer"].includes(account.role))return action("Run isolated tests",`/v1/jobs/${j.work_item_id}/execute`);if(j.state==="awaiting_human_decision"&&account.role==="owner")return action("Approve",`/v1/jobs/${j.work_item_id}/decision`,{decision:"approve"})+action("Reject",`/v1/jobs/${j.work_item_id}/decision`,{decision:"reject"});if(j.state==="awaiting_human_decision"&&account.role==="reviewer")return "Review evidence; Owner decision required";if(["approved","rejected"].includes(j.state)&&account.role==="owner")return action("Close",`/v1/jobs/${j.work_item_id}/close`);return "—"}
$("dashboard-output").onclick=async e=>{const b=e.target.closest(".dash-action");if(!b)return;try{await api(b.dataset.path,{method:"POST",body:b.dataset.body});await loadDashboard();message("Workflow updated.")}catch(err){message(err.message,true)}};
$("refresh-dashboard").onclick=loadDashboard;
async function loadClassroom(){try{const d=await api("/v1/students");$("classroom-output").innerHTML=`<table><caption>Student progress</caption><thead><tr><th scope="col">Student</th><th scope="col">XP</th><th scope="col">Rank</th><th scope="col">Completed</th></tr></thead><tbody>${d.students.map(s=>`<tr><td>${escapeText(s.username)}</td><td>${escapeText(s.progress.xp)}</td><td>${escapeText(s.progress.rank)}</td><td>${escapeText(s.progress.completed_quests.length)}</td></tr>`).join("")}</tbody></table>`}catch(err){message(err.message,true)}}
$("refresh-classroom").onclick=loadClassroom;
async function loadSystemReadiness(){try{const d=await api("/v1/system/readiness");$("system-output").replaceChildren(...Object.entries(d.items).map(([name,item])=>{const card=document.createElement("article");card.className=`readiness-item status-${item.status}`;const title=document.createElement("strong");title.textContent=name.replaceAll("_"," ");const status=document.createElement("span");status.className="pill";status.textContent=item.status.replaceAll("_"," ");const summary=document.createElement("p");summary.textContent=item.summary;card.append(title,status,summary);return card}));message(d.overall==="ready"?"All configured systems are ready.":"Core is ready. Optional setup items are shown below.")}catch(err){message(err.message,true)}}
$("refresh-system").onclick=loadSystemReadiness;
async function loadAccounts(){try{const d=await api("/v1/accounts");$("accounts-output").innerHTML=`<table><caption>Account permissions</caption><thead><tr><th scope="col">Username</th><th scope="col">Role</th><th scope="col">Status</th><th scope="col">Control</th></tr></thead><tbody>${d.accounts.map(a=>`<tr><td>${escapeText(a.username)}</td><td>${escapeText(a.role)}</td><td>${a.active?"Active":"Disabled"}</td><td>${a.role==="owner"?"Protected":`<button class="account-toggle secondary" data-id="${a.account_id}" data-active="${!a.active}">${a.active?"Disable":"Enable"}</button>`}</td></tr>`).join("")}</tbody></table>`}catch(err){message(err.message,true)}}
$("accounts-output").onclick=async e=>{const b=e.target.closest(".account-toggle");if(!b)return;try{await api(`/v1/accounts/${b.dataset.id}/active`,{method:"POST",body:JSON.stringify({active:b.dataset.active==="true"})});await loadAccounts();message("Account status updated.")}catch(err){message(err.message,true)}};
$("account-form").onsubmit=async e=>{e.preventDefault();try{await api("/v1/accounts",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();await loadAccounts();message("Account created.")}catch(err){message(err.message,true)}};

function mobileStatus(device){if(device.revoked_at)return"Revoked";if(new Date(device.expires_at)<=new Date())return"Expired";return"Active"}
async function loadMobileDevices(){try{const d=await api("/v1/mobile/devices");$("mobile-devices-output").innerHTML=`<table><caption>Paired mobile devices</caption><thead><tr><th scope="col">Device</th><th scope="col">Mode</th><th scope="col">Status</th><th scope="col">Expires</th><th scope="col">Control</th></tr></thead><tbody>${d.devices.map(device=>`<tr><td>${escapeText(device.label)}</td><td>${escapeText(device.mode.replaceAll("_"," "))}</td><td>${escapeText(mobileStatus(device))}</td><td>${escapeText(new Date(device.expires_at).toLocaleString())}</td><td>${device.revoked_at?"—":`<button class="revoke-mobile secondary" data-id="${device.device_id}">Revoke</button>`}</td></tr>`).join("")}</tbody></table>`}catch(err){message(err.message,true)}}
$("mobile-pairing-form").onsubmit=async e=>{e.preventDefault();try{const data=await api("/v1/mobile/pairings",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const pretty=`${data.code.slice(0,4)} ${data.code.slice(4)}`;$("mobile-pairing-output").innerHTML=`<span class="muted">One-time code for ${escapeText(data.label)}</span><strong class="pair-code">${escapeText(pretty)}</strong><span class="muted">Mode: ${escapeText(data.mode.replaceAll("_"," "))}. Expires ${escapeText(new Date(data.expires_at).toLocaleTimeString())}.</span>`;message("Pairing code created. Enter it on the phone before it expires.")}catch(err){message(err.message,true)}};
$("mobile-devices-output").onclick=async e=>{const b=e.target.closest(".revoke-mobile");if(!b)return;try{await api(`/v1/mobile/devices/${b.dataset.id}/revoke`,{method:"POST",body:"{}"});await loadMobileDevices();message("Phone access revoked.")}catch(err){message(err.message,true)}};
$("refresh-mobile").onclick=loadMobileDevices;

$("password-form").onsubmit=async e=>{e.preventDefault();try{await api("/v1/auth/password",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();message("Password changed. Other sessions were signed out.")}catch(err){message(err.message,true)}};
function escapeText(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function bootstrap(){if(window.SADMobile&&!window.SADMobile.ensurePaired())return;if(token){try{await enter()}catch(error){sessionStorage.removeItem("sad_token");token="";if(!window.SADMobile?.handleApiError?.(error.message))$("login-error").textContent="Please sign in again."}}}
renderLessonLibrary();
bootstrap();
